apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: whoareyou
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 7000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoareyou
spec:
  selector:
    matchLabels:
      app: whoareyou
  replicas: 2
  template:
    metadata:
      labels:
        app: whoareyou
    spec:
      containers:
      - name: whoareyou
        image: homelala/flask-test-1
        imagePullPolicy: Always
        ports:
        - containerPort: 7000